Based on the provided LLVM IR code, here is the corresponding C source code:

```c
int modp(int a, int b) {
  if (a > 0) {
    int x = 0;
    int y = 1;
    do {
      y = (y << 1) % b;
      x++;
    } while (x != a);
    return y;
  } else {
    return 1;
  }
}
```

Note that I've used the name `modp` for the function, as the original name `_Z4modpii` is a mangled name generated by the C++ compiler, and I've assumed that the function is intended to calculate the modular exponentiation. If you need to use a different name, please let me know.