#include <iostream>
using namespace std;
int main()
{
int w,m,d,a;
w=0;
m=1;
d=0;
a=1;
cin >> "%d",&w);
w=w-1;
d=d+13;
a=(d-(d/7)*7+w);
if(a==5) cout << "%d\n",m);
if(a==12) cout << "%d\n",m);
d=d+31;
m=m+1;
a=(d-(d/7)*7+w);
if(a==5) cout << "%d\n",m);
if(a==12) cout << "%d\n",m);
d=d+28;
m=m+1;
a=(d-(d/7)*7+w);
if(a==5) cout << "%d\n",m);
if(a==12) cout << "%d\n",m);
d=d+31;
m=m+1;
a=(d-(d/7)*7+w);
if(a==5) cout << "%d\n",m);
if(a==12) cout << "%d\n",m);
d=d+30;
m=m+1;
a=(d-(d/7)*7+w);
if(a==5) cout << "%d\n",m);
if(a==12) cout << "%d\n",m);
d=d+31;
m=m+1;
a=(d-(d/7)*7+w);
if(a==5) cout << "%d\n",m);
if(a==12) cout << "%d\n",m);
d=d+30;
m=m+1;
a=(d-(d/7)*7+w);
if(a==5) cout << "%d\n",m);
if(a==12) cout << "%d\n",m);
d=d+31;
m=m+1;
a=(d-(d/7)*7+w);
if(a==5) cout << "%d\n",m);
if(a==12) cout << "%d\n",m);
d=d+31;
m=m+1;
a=(d-(d/7)*7+w);
if(a==5) cout << "%d\n",m);
if(a==12) cout << "%d\n",m);
d=d+30;
m=m+1;
a=(d-(d/7)*7+w);
if(a==5) cout << "%d\n",m);
if(a==12) cout << "%d\n",m);
d=d+31;
m=m+1;
a=(d-(d/7)*7+w);
if(a==5) cout << "%d\n",m);
if(a==12) cout << "%d\n",m);
d=d+30;
m=m+1;
a=(d-(d/7)*7+w);
if(a==5) cout << "%d\n",m);
if(a==12) cout << "%d\n",m);
}